name: build_and_cache

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix ❄️"
        uses: nixbuild/nix-quick-install-action@v4
        with:
          nix_version: 3.0pre20200829_f156513
          nix_conf: experimental-features = nix-command flakes

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v6
        with:
          name: bbjubjub2494-coprocessing
          authToken: "${{ secrets.CACHIX_TOKEN }}"

      - name: "Build and Cache 🚀"
        run:
          nix build
